trigger:
  - master
pool:
  vmImage: 'ubuntu-latest'
variables:
  system.debug: true
steps:
    - task: NodeTool@0
      inputs:    
        versionSpec: '10.x'
    - script:
        npm install @angular/cli -g
      workingDirectory: './'
    - script:
        npm install
      workingDirectory: './'
    - script:  
        ng build 
      displayName: 'ng build --prod --base-href ./'
      workingDirectory: './'        
    - task: AzureRmWebAppDeployment@4
      displayName: 'Azure App Service Deploy: Angular'
      inputs:
        azureSubscription: 'app2dfrango - Azure'
        WebAppName: app2dfrango
        packageForLinux: dist/
  